
export const USER_VIEW_MAIN_SPEAKER = "USER_VIEW_MAIN_SPEAKER";
export const USER_VIEW_POI_SPEAKER = "USER_VIEW_POI_SPEAKER";
export const USER_VIEW_POI_WAITING_MAIN_SPEAKER = "USER_VIEW_POI_WAITING_MAIN_SPEAKER";
export const USER_VIEW_INTRO = "USER_VIEW_INTRO";
export const USER_VIEW_PREP = "USER_VIEW_PREP";